### ISSUE TITLE
Add HTML datatype to the project and on it's items

### ISSUE THREAD

**Issue by alexandredljn** [lajavaness/annotto#23]
Add the html datatype to the project as an available type, as well as to the items.

There should be no impact on the labeling types.

You should use the `sanitize` function of `shared/utils/htmlUtils` in order to clean up the HTML code and safely insert external content into the annotation page.

Currently the TextItemContainer component is used to display html content. It is necessary to remove the functionality of this component and create a new component to separate the display of content in text or in html depending on the type of project.

**Comment by manodupont** [comment]
can you link this issue with the PR associated please ?

**Comment by manodupont** [comment]
@alexandredljn  Ive done it! No worries
