### ISSUE TITLE
All in one docker ljnrepo/annotto 1.2.6 is not working as expected

### ISSUE THREAD

**Issue by r3n4ud** [lajavaness/annotto#42]
**Bug description**
We retrieve and run the latest ljnrepo/annotto image as specified:
```bash
docker run --rm -d --name annotto -p 3000:3000 ljnrepo/annotto:latest
```
We can log in through http://localhost:3000/ and we get the following home listing existing projects:

![image](https://user-images.githubusercontent.com/699794/226839238-0880ae3e-1a73-4417-bc96-4c3833cf078a.png)

Accessing any project by clicking on its name or on the related `Annotate` link yields to a never ending loader view with a `An error occured` notification.

**To Reproduce**
1. Go to http://localhost:3000
2. Sign in to the admin account, click on `Sign In`
3. Click on `DEMO Zone and Text : CV - Extraction` (for instance, or any another project link to project/id/)

**Expected behavior**
We don't know yet what should happen here :wink: 

**Screenshots**
N/A see previous sections

**Desktop (please complete the following information):**
 - OS: GNU/Linux Debian 11
 - Browser: Firefox 112.0b4 and chrome 110.0.5481.177 among others tested
 - Version: N/A

**Additional context**
No particular suspicious logs from docker logs...

Did I miss something (at keycloak level or something)?

**Comment by manodupont** [comment]
@r3n4ud 
There is indeed something missing in the configuration file. KEYCLOAK_ADMIN_CLI_SECRET was missing so Keycloak can make call to master realm to fetch all users correctly.

Next build will contain the correct token.

**Comment by r3n4ud** [comment]
Tested today, seems to work as expected.
Thanks!
