### ISSUE TITLE
Format of Item file (JSONL file) as described in the docs terminates Annotto container 

### ISSUE THREAD

**Issue by syjrr** [lajavaness/annotto#44]
**Describe the bug**
When trying to add items to a (new or existing) project according to the structure of the 'item file' that is given as an example in the section 'Create projet' of the documentation (https://lajavaness.github.io/annotto-docs/fr/docs/user-manual/create-project), 
an error is returned to the user and the Annotto docker container is then found exited.

Note that a possible fix is shared at the end of this issue. 

**To Reproduce**
1. Go to https://lajavaness.github.io/annotto-docs/docs/user-manual/create-project#mode-texte 
2. Click on 'copy' button appearing when flying over the JSONL code example (items.jsonline)
3. Paste in a new UTF8 text file and save as 'items.jsonline'
4. In Annotto, select an example projet and '...' then 'Adminstration' and 'Files' tab of the project
5. go to 'Item file (JSONL file)' and click on 'Add' and select 'items.jsonline' file you have just saved and Open
6. Click on blue 'Save' button on the top of the page
7. See error : << An error has occurred
Could not parse row {"datatype": "text","uuid": "e0870093-180d-46ac-9d...>>
8. Click on page reload in your browser
9. See the error 'The connection failed'
10. on the server execute the command to list both stopped and running containers
docker ps -a
11. see the 'Exited' status of the annotto container

**Expected behavior**
Annotto should add three items to the selected project.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 102.10.0esr (64 bits)

**Additional context**
Server is on Docker 23.0.1 on Debian GNU/Linux 11 (bullseye) with Annotto release 1.2.7 (2023-03-30)

It seems that files in JSONL format usually do not have a comma separator between lines (in addition to LF or CR+LF separator), as it is strangely present in the example of 'items.jsonline' file, and somehow it is less strange that it does not work.

After suppressing commas between lines (at the end of each JSON line inside the jsonline file, except le last one which had no comma at the end) and keeping LF or CR+LF separators, the item file adding function of Annotto seems to work well.

One suggestion is to update the Annotto Documentation, by suppressing comma separators between lines in the example(s)*.
*: It has not been tested yet, but it could be the same problem with other jsonline examples like images.jsonline which also have comma separators which might also need to be removed.

see also : 
https://github.com/lajavaness/annotto-docs/blob/main/docs/user-manual/create-project.md

**Comment by manodupont** [comment]
Fixed in lajavaness/annotto-docs#14
